#ifndef CLIENTTEMPLATE_CLIENT_H_
#define CLIENTTEMPLATE_CLIENT_H_

#define TEMPLATE_INTERFACE_METHOD "\n\
		/** \n\
		  * <methodComment>\n\
<paramsComments>\
		  */ \n\
		<aliases>\
        virtual <returnType> <methodName>(<parameters>) = 0;\n\
"

#define TEMPLATE_INTERFACE_SIGNAL "\
		<signalTypeDefinition>;\n\
		Poco::BasicEvent <<signalType>> <signalName>;\n\
		\n\
"

#define TEMPLATE_STRUCTS "\
<namespaceStart>\
       struct <structName> {\n\
				\n\
				static std::string name(){\n\
					static std::string n = \"<structName>\";\n\
					return n;\n\
				}\n\
				static const ::TBS::Services::Introspection::Struct & introspection();\n\
				\n //members \n\
				<members>\n\
				\n\
			};\n\
<namespaceEnd>\n\
\n"


#define TEMPLATE_CLASS "\
<namespaceStart>\
	   /** <classComment> */\n\
       class <className> {\n\
			public:\n\
				typedef Poco::SharedPtr <<className>> Ptr;\n\
				\n\
				virtual ~<className>(){}\n\
				\n\
				static std::string name(){\n\
					static std::string n = \"<interfaceName>\";\n\
					return n;\n\
				}\n\
				static const ::TBS::Services::Introspection::Class & introspection();\n\
				\n //methods \n\
				<methods>\n\
				\n //signals \n\
				<signals>\n\
				\n\
			};\n\
<namespaceEnd>\n\
\n"


#define TEMPLATE_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
#ifndef _<STUBNAME>_H_\n\
#define _<STUBNAME>_H_\n\
\n\
#include <Poco/SharedPtr.h>\n\
#include <Poco/BasicEvent.h>\n\
#include \"TBS/Services/Types.h\"\n\
#include <string>\n\
#include <vector>\n\
#include <map>\n\
\n\
namespace TBS{ namespace Services{ namespace Introspection{ class Class; struct Struct; } } } \n\
\n\
\n\
<structs>\n\
\n\
<classes>\n\
#endif //_<STUBNAME>_H_\n\
"

#define CPP_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
#include \"TBS/Services/Introspection.h\"\n\
<includes>\n\
\n\
\n\
<classes>\n\
"

#define CPP_CLASS "\
<namespaceStart>\
		::TBS::Services::Introspection::Class __introspection<className>(){\n\
			<introspection>\n\
		}\n\
	   const ::TBS::Services::Introspection::Class & <className>::introspection(){\n\
			static ::TBS::Services::Introspection::Class c(__introspection<className>());\n\
			return c;\n\
	   }\n\
<namespaceEnd>\n\
\n"

#define CPP_STRUCT "\
<namespaceStart>\
		::TBS::Services::Introspection::Struct __introspection<structName>(){\n\
			<introspection>\n\
		}\n\
	   const ::TBS::Services::Introspection::Struct & <structName>::introspection(){\n\
			static ::TBS::Services::Introspection::Struct s(__introspection<structName>());\n\
			return c;\n\
	   }\n\
<namespaceEnd>\n\
\n"

#endif
