/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#include "TBS/Services/Introspection.h"
#include "HAL/API/BioRadar.h"



namespace HAL { 
	namespace API { 
		namespace BioRadar { 
		::TBS::Services::Introspection::Class __introspectionIBase(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("HAL");
cnmspc.push_back("API");
cnmspc.push_back("BioRadar");
::TBS::Services::Introspection::Class c("HAL.API.BioRadar.Base", "Base", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("GoMin", "");
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GoMax", "");
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GoRel", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("speed", "i", "-100 to 100"));
	c.methods.push_back(m);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IBase::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIBase());
			return c;
	   }
 } 
 } 
 } 




