/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
///includes
#include "HAL/API/CameraSvc_Json.h"
#include "Client/Camera_Json.h"
#include "Server/Camera_Json.h"

#include <TBS/Services/Json/JsonServicesImpl.h>

//convertors
namespace jsonrpc {}

namespace HAL { 
	namespace API { 
		namespace Camera { 
			namespace Json { 
	   Client::Client(const TBS::Services::JsonClientChannel & ch) : 
	       ch(ch){
	   }
	   Client::~Client(){}
	   HAL::API::Camera::ICamera & Client::Camera(){
   if (!camera_) {      camera_ =  new HAL::API::Camera::Stub::Camera_JsonClient(::TBS::Services::convert(ch));
   }   return *camera_;
}

	   
	   
	   Server::Server(const TBS::Services::JsonServerChannel & ch) : 
	   	   channel(new TBS::Services::JsonCommChannelHolder(ch)){
		   
	    } 
	    Server::~Server(){}
	    void Server::start(){ 
	   	   channel.cast<TBS::Services::JsonCommChannelHolder>()->interface.StartListening();
	    } 
	    void Server::stop(){ 
	   	   channel.cast<TBS::Services::JsonCommChannelHolder>()->interface.StopListening();
	    } 
	    
	   TBS::Services::IServer::Ptr Server::createCamera(HAL::API::Camera::ICamera::Ptr impl){
   return new TBS::Services::JsonServerImpl<HAL::API::Camera::ICamera, HAL::API::Camera::Stub::Camera_JsonServer>(this->channel.cast<TBS::Services::JsonCommChannelHolder>()->interface, impl);
}

 } 
 } 
 } 
 } 



