#ifndef _NO_DBUS 
/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
///includes
#include "HAL/API/CameraSvc_DBus.h"
#include "Client/Camera_DBus.h"
#include "Server/Camera_DBus.h"

#include <TBS/Services/DBus/DBusServicesImpl.h>



namespace HAL { 
	namespace API { 
		namespace Camera { 
			namespace DBus { 
	   Client::Client(TBS::Services::ICommChannelHolder::Ptr ch) : 
	       ch(ch), comChannelHolder(new TBS::Services::CommunicationChannelHolder(ch)) {
	   }
	   Client::Client() : 
		   ch(TBS::Services::DBusCommChannelProvider::getDefaultCommChannel()), comChannelHolder(new TBS::Services::CommunicationChannelHolder(ch)) {
	   }
	   Client::~Client(){ 
	   }
	   HAL::API::Camera::ICamera & Client::Camera(){
   if (!camera_) {      camera_ =  new TBS::Services::DBusClientImpl<HAL::API::Camera::Stub::Camera_DBusClient>(comChannelHolder->getConnection());
   }   return *camera_;
}

	   
	   
	   Server::Server(TBS::Services::ICommChannelHolder::Ptr ch) : 
	   	   ch(ch){
		   
	    } 
		Server::Server() : 
	   	   ch(TBS::Services::DBusCommChannelProvider::getDefaultCommChannel()){
		   
	    } 
	    Server::~Server(){ 
	    }
	    
	   TBS::Services::IServer::Ptr Server::createCamera(HAL::API::Camera::ICamera::Ptr impl){
   return new TBS::Services::DBusServerImpl<HAL::API::Camera::ICamera, HAL::API::Camera::Stub::Camera_DBusServer>(ch, impl);
}

 } 
 } 
 } 
 } 


#endif 

