/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#include "TBS/Services/Introspection.h"
#include "HAL/API/Movement.h"



namespace HAL { 
	namespace API { 
		::TBS::Services::Introspection::Class __introspectionIMovement(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("HAL");
cnmspc.push_back("API");
::TBS::Services::Introspection::Class c("HAL.API.Movement", "Movement", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("Move", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("speedLeft", "d", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("speedRight", "d", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("Stop", "");
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("SetPosition", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("posLeft", "x", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("posRight", "x", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetStatus", "");
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("speedLeft", "d", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("speedRight", "d", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("posLeft", "x", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("posRight", "x", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Signal s("StatusChanged", "");
  s.arguments.push_back(::TBS::Services::Introspection::Argument("speedLeft", "d", ""));
  s.arguments.push_back(::TBS::Services::Introspection::Argument("speedRight", "d", ""));
  s.arguments.push_back(::TBS::Services::Introspection::Argument("posLeft", "x", ""));
  s.arguments.push_back(::TBS::Services::Introspection::Argument("posRight", "x", ""));
	c.signals.push_back(s);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IMovement::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIMovement());
			return c;
	   }
 } 
 } 




