/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#include "TBS/Services/Introspection.h"
#include "HAL/API/Remote.h"



namespace HAL { 
	namespace Remote { 
		::TBS::Services::Introspection::Class __introspectionIMovement(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("HAL");
cnmspc.push_back("Remote");
::TBS::Services::Introspection::Class c("HAL.Remote.Movement", "Movement", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("Move", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("speedLeft", "d", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("speedRight", "d", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("Stop", "");
	c.methods.push_back(m);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IMovement::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIMovement());
			return c;
	   }
 } 
 } 




