/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
///includes
#include "HAL/API/RemoteSvc_Json.h"
#include "Client/Remote_Json.h"
#include "Server/Remote_Json.h"

#include <TBS/Services/Json/JsonServicesImpl.h>

//convertors
namespace jsonrpc {}

namespace HAL { 
	namespace Remote { 
		namespace Json { 
	   Client::Client(const TBS::Services::JsonClientChannel & ch) : 
	       ch(ch){
	   }
	   Client::~Client(){}
	   HAL::Remote::IMovement & Client::Movement(){
   if (!movement_) {      movement_ =  new HAL::Remote::Stub::Movement_JsonClient(::TBS::Services::convert(ch));
   }   return *movement_;
}

	   
	   
	   Server::Server(const TBS::Services::JsonServerChannel & ch) : 
	   	   channel(new TBS::Services::JsonCommChannelHolder(ch)){
		   
	    } 
	    Server::~Server(){}
	    void Server::start(){ 
	   	   channel.cast<TBS::Services::JsonCommChannelHolder>()->interface.StartListening();
	    } 
	    void Server::stop(){ 
	   	   channel.cast<TBS::Services::JsonCommChannelHolder>()->interface.StopListening();
	    } 
	    
	   TBS::Services::IServer::Ptr Server::createMovement(HAL::Remote::IMovement::Ptr impl){
   return new TBS::Services::JsonServerImpl<HAL::Remote::IMovement, HAL::Remote::Stub::Movement_JsonServer>(this->channel.cast<TBS::Services::JsonCommChannelHolder>()->interface, impl);
}

 } 
 } 
 } 



