/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#include "TBS/Services/Introspection.h"
#include "HAL/API/UltraSound.h"



namespace HAL { 
	namespace API { 
		namespace UltraSound { 
		::TBS::Services::Introspection::Class __introspectionIUltraSound(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("HAL");
cnmspc.push_back("API");
cnmspc.push_back("UltraSound");
::TBS::Services::Introspection::Class c("HAL.API.UltraSound.UltraSound", "UltraSound", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("Reconnect", "");
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetStatus", "");
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("frontSensors", "[TouchSensors]", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("backSensors", "[TouchSensors]", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("isValid", "b", ""));
	c.methods.push_back(m);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IUltraSound::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIUltraSound());
			return c;
	   }
 } 
 } 
 } 




