/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
///includes
#include "HWIOSvc_Json.h"
#include "Client/HWIO_Json.h"
#include "Server/HWIO_Json.h"

#include <TBS/Services/Json/JsonServicesImpl.h>


namespace TBS { 
	namespace TSeries { 
		namespace Services { 
			namespace HWIO { 
				namespace Json { 
	   Client::Client(const TBS::Services::JsonClientChannel & ch) : 
	       ch(ch){
	   }
	   TBS::TSeries::Services::HWIO::IServices & Client::Services(){
   if (!services_) {      services_ =  new TBS::TSeries::Services::HWIO::Stub::Services_JsonClient(ch.hostName(), ch.port());
   }   return *services_;
}
TBS::TSeries::Services::HWIO::ISmartController & Client::SmartController(){
   if (!smartcontroller_) {      smartcontroller_ =  new TBS::TSeries::Services::HWIO::Stub::SmartController_JsonClient(ch.hostName(), ch.port());
   }   return *smartcontroller_;
}
TBS::TSeries::Services::HWIO::IInternalRelay & Client::InternalRelay(){
   if (!internalrelay_) {      internalrelay_ =  new TBS::TSeries::Services::HWIO::Stub::InternalRelay_JsonClient(ch.hostName(), ch.port());
   }   return *internalrelay_;
}

	   
	   
	   Server::Server(const TBS::Services::JsonServerChannel & ch) : 
	   	   channel(new TBS::Services::JsonCommChannelHolder(ch.port())){
		   
	    } 
	    void Server::start(){ 
	   	   channel.cast<TBS::Services::JsonCommChannelHolder>()->interface.StartListening();
	    } 
	    void Server::stop(){ 
	   	   channel.cast<TBS::Services::JsonCommChannelHolder>()->interface.StopListening();
	    } 
	    
	   TBS::Services::IServer::Ptr Server::createServices(TBS::TSeries::Services::HWIO::IServices::Ptr impl){
   return new TBS::Services::JsonServerImpl<TBS::TSeries::Services::HWIO::IServices, TBS::TSeries::Services::HWIO::Stub::Services_JsonServer>(this->channel.cast<TBS::Services::JsonCommChannelHolder>()->interface, impl);
}
TBS::Services::IServer::Ptr Server::createSmartController(TBS::TSeries::Services::HWIO::ISmartController::Ptr impl){
   return new TBS::Services::JsonServerImpl<TBS::TSeries::Services::HWIO::ISmartController, TBS::TSeries::Services::HWIO::Stub::SmartController_JsonServer>(this->channel.cast<TBS::Services::JsonCommChannelHolder>()->interface, impl);
}
TBS::Services::IServer::Ptr Server::createInternalRelay(TBS::TSeries::Services::HWIO::IInternalRelay::Ptr impl){
   return new TBS::Services::JsonServerImpl<TBS::TSeries::Services::HWIO::IInternalRelay, TBS::TSeries::Services::HWIO::Stub::InternalRelay_JsonServer>(this->channel.cast<TBS::Services::JsonCommChannelHolder>()->interface, impl);
}

 } 
 } 
 } 
 } 
 } 



