/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _HWIO_SERVICE_JSON_H_
#define _HWIO_SERVICE_JSON_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <TBS/Services/Services.h>
#include <TBS/Services/Json/JsonServices.h>
///includes
#include "HWIO.h"


namespace TBS { 
	namespace TSeries { 
		namespace Services { 
			namespace HWIO { 
				namespace Json { 
       class Client {
			public:
				typedef Poco::SharedPtr <Client> Ptr;
				
				Client(const TBS::Services::JsonClientChannel & ch);
				
				
 //methods 
				TBS::TSeries::Services::HWIO::IServices & Services();
TBS::TSeries::Services::HWIO::ISmartController & SmartController();
TBS::TSeries::Services::HWIO::IInternalRelay & InternalRelay();

				
		private: 
				TBS::Services::JsonClientChannel ch;
				TBS::TSeries::Services::HWIO::IServices::Ptr services_;
TBS::TSeries::Services::HWIO::ISmartController::Ptr smartcontroller_;
TBS::TSeries::Services::HWIO::IInternalRelay::Ptr internalrelay_;

			};
			
			
		class Server {
			public:
				typedef Poco::SharedPtr<Server> Ptr;
				Server(const TBS::Services::JsonServerChannel & ch);
				
				void start();
				void stop();
			public:
				TBS::Services::IServer::Ptr createServices(TBS::TSeries::Services::HWIO::IServices::Ptr impl);
TBS::Services::IServer::Ptr createSmartController(TBS::TSeries::Services::HWIO::ISmartController::Ptr impl);
TBS::Services::IServer::Ptr createInternalRelay(TBS::TSeries::Services::HWIO::IInternalRelay::Ptr impl);

				
			private:
				TBS::Services::ICommChannelHolder::Ptr channel;
		};
 } 
 } 
 } 
 } 
 } 

#endif //_HWIO_SERVICE_H_

