/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _HWIO_H_
#define _HWIO_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>


namespace TBS { 
	namespace TSeries { 
		namespace Services { 
			namespace HWIO { 
       class IServices {
			public:
				typedef Poco::SharedPtr <IServices> Ptr;
				
				virtual ~IServices(){}
				
				static std::string name(){
					static std::string n = "TBS.TSeries.Services.HWIO.Services";
					return n;
				}
				
 //methods 
				        virtual std::vector< std::string > Available() = 0;
        virtual void Reload() = 0;

				
 //signals 
				
				
			};
 } 
 } 
 } 
 } 


namespace TBS { 
	namespace TSeries { 
		namespace Services { 
			namespace HWIO { 
       class ISmartController {
			public:
				typedef Poco::SharedPtr <ISmartController> Ptr;
				
				virtual ~ISmartController(){}
				
				static std::string name(){
					static std::string n = "TBS.TSeries.Services.HWIO.SmartController";
					return n;
				}
				
 //methods 
				        virtual void Relay1(const int32_t & timeout) = 0;
        virtual void Relay2(const int32_t & timeout) = 0;
        virtual void GPOut1(const int32_t & status) = 0;
        virtual void GPOut2(const int32_t & status) = 0;
        virtual int32_t GPIn1Value() = 0;
        virtual int32_t GPIn2Value() = 0;

				
 //signals 
						struct GPIn1ChangedArg { 
int32_t value;
int32_t oldvalue;
};
		Poco::BasicEvent <GPIn1ChangedArg> GPIn1Changed;
		
		typedef int32_t GPIn2ChangedArg;
		Poco::BasicEvent <GPIn2ChangedArg> GPIn2Changed;
		

				
			};
 } 
 } 
 } 
 } 


namespace TBS { 
	namespace TSeries { 
		namespace Services { 
			namespace HWIO { 
       class IInternalRelay {
			public:
				typedef Poco::SharedPtr <IInternalRelay> Ptr;
				
				virtual ~IInternalRelay(){}
				
				static std::string name(){
					static std::string n = "TBS.TSeries.Services.HWIO.InternalRelay";
					return n;
				}
				
 //methods 
				        virtual void Relay(const int32_t & timeoutMs) = 0;

				
 //signals 
				
				
			};
 } 
 } 
 } 
 } 



#endif //_HWIO_H_

