/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
///includes
#include "HWIOSvc_DBus.h"
#include "Client/HWIO_DBus.h"
#include "Server/HWIO_DBus.h"

#include <TBS/Services/DBus/DBusServicesImpl.h>



namespace TBS { 
	namespace TSeries { 
		namespace Services { 
			namespace HWIO { 
				namespace DBus { 
	   Client::Client(TBS::Services::ICommChannelHolder::Ptr ch) : 
	       ch(ch), comChannelHolder(new TBS::Services::CommunicationChannelHolder(ch)) {
	   }
	   Client::Client() : 
		   ch(TBS::Services::DBusCommChannelProvider::getDefaultCommChannel()), comChannelHolder(new TBS::Services::CommunicationChannelHolder(ch)) {
	   }
	   TBS::TSeries::Services::HWIO::IServices & Client::Services(){
   if (!services_) {      services_ =  new TBS::Services::DBusClientImpl<TBS::TSeries::Services::HWIO::Stub::Services_DBusClient>(comChannelHolder->getConnection());
   }   return *services_;
}
TBS::TSeries::Services::HWIO::ISmartController & Client::SmartController(){
   if (!smartcontroller_) {      smartcontroller_ =  new TBS::Services::DBusClientImpl<TBS::TSeries::Services::HWIO::Stub::SmartController_DBusClient>(comChannelHolder->getConnection());
   }   return *smartcontroller_;
}
TBS::TSeries::Services::HWIO::IInternalRelay & Client::InternalRelay(){
   if (!internalrelay_) {      internalrelay_ =  new TBS::Services::DBusClientImpl<TBS::TSeries::Services::HWIO::Stub::InternalRelay_DBusClient>(comChannelHolder->getConnection());
   }   return *internalrelay_;
}

	   
	   
	   Server::Server(TBS::Services::ICommChannelHolder::Ptr ch) : 
	   	   ch(ch){
		   
	    } 
		Server::Server() : 
	   	   ch(TBS::Services::DBusCommChannelProvider::getDefaultCommChannel()){
		   
	    } 
	    
	   TBS::Services::IServer::Ptr Server::createServices(TBS::TSeries::Services::HWIO::IServices::Ptr impl){
   return new TBS::Services::DBusServerImpl<TBS::TSeries::Services::HWIO::IServices, TBS::TSeries::Services::HWIO::Stub::Services_DBusServer>(ch, impl);
}
TBS::Services::IServer::Ptr Server::createSmartController(TBS::TSeries::Services::HWIO::ISmartController::Ptr impl){
   return new TBS::Services::DBusServerImpl<TBS::TSeries::Services::HWIO::ISmartController, TBS::TSeries::Services::HWIO::Stub::SmartController_DBusServer>(ch, impl);
}
TBS::Services::IServer::Ptr Server::createInternalRelay(TBS::TSeries::Services::HWIO::IInternalRelay::Ptr impl){
   return new TBS::Services::DBusServerImpl<TBS::TSeries::Services::HWIO::IInternalRelay, TBS::TSeries::Services::HWIO::Stub::InternalRelay_DBusServer>(ch, impl);
}

 } 
 } 
 } 
 } 
 } 



