/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */

function BioRadar(params){
  var settings = {
      url: params.url + "HAL.API.BioRadar.BioRadar",
      username: params.username,
      password: params.password,
  };
  
  
 //methods 
          this.Enable = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "Enable",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.Disable = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "Disable",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GoMinBase = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GoMinBase",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GoMaxBase = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GoMaxBase",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GoRelBase = function(_speed){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GoRelBase",
    		params: {speed: _speed},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GoMinAntenna = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GoMinAntenna",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GoMaxAntenna = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GoMaxAntenna",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GoRelAntenna = function(_speed){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GoRelAntenna",
    		params: {speed: _speed},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GetMotorStatus = function(_isBase){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GetMotorStatus",
    		params: {isBase: _isBase},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }
        this.GetAntenaStatus = function(){
		var jdata;
    	$.jsonrpcTBS({
    		url: settings.url,
    		username: settings.username,
    		password: settings.password,
    		method: "GetAntenaStatus",
    		params: {},
		onRequest: function (r) {
			//console.log(r);
		},
		onResponse: function (r) {
			//console.log(r);
		},
    		success: function (response) {
    		  jdata = response; //$.parseJSON(response);
		      //return jdata;
    		},
    		fault: function (response, errordata) {
				throw('Failed: ' + response);
    		},
    		error: function (request, status, error) {
    			throw('Failed: ' + error + ')');
    		}
    	});
		
		return jdata; 
        }

}



