#ifndef dnCLIENTTEMPLATE_CLIENT_H_
#define dnCLIENTTEMPLATE_CLIENT_H_
/*
#define TEMPLATE_CLIENT_METHOD "\
        <returnType> <methodName>(<parameters>){\n\
            ::Json::Value p;\n\
            <parameterAssign>\n\
            <returnStatement>\n\
        }\n\
"
*/



#define TEMPLATE_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
#ifndef _<STUBNAME>_SERVICE_Dotnet_H_\n\
#define _<STUBNAME>_SERVICE_Dotnet_H_\n\
\n\
#include <Poco/SharedPtr.h>\n\
#include <Poco/BasicEvent.h>\n\
#include <string>\n\
#include <vector>\n\
#include <map>\n\
#include <memory>\n\
#include <TBS/Services/Services.h>\n\
#include <TBS/Services/DotNet/DotNetServices.h>\n\
///includes\n\
<includes>\n\
\n\
\n\
<namespaceStart>\
       class Client {\n\
			public:\n\
				typedef Poco::SharedPtr <Client> Ptr;\n\
				\n\
				Client(const TBS::Services::DotNetClientParams & params);\n\
				~Client();\n\
				\n\
				\n //methods \n\
				<clients>\n\
				\n\
		private: \n\
				TBS::Services::DotNetClientParams params;\n\
				<private>\n\
			};\n\
			\n\
			\n\
<namespaceEnd>\n\
#endif //_<STUBNAME>_SERVICE_Dotnet_H_\n\
"


#define TEMPLATE_CPP_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
///includes\n\
<includes>\n\
\n\
//convertors\n\
<convertors>\n\
\n\
<namespaceStart>\
	   Client::Client(const TBS::Services::DotNetClientParams & params) : \n\
	       params(params){\n\
	   }\n\
	   Client::~Client(){}\n\
	   <clientMethods>\n\
	   \n\
<namespaceEnd>\n\
\n\
"

#endif
