#ifndef CLIENTTEMPLATE_dnT_H_
#define CLIENTTEMPLATE_dnT_H_

#define TEMPLATE_CLIENT_METHOD "\
        <returnType> <methodName>(<parameters>){\n\
            std::string url;\n\
            url.append(\"/<methodName>?\");\n\
            <parameterAssign>\n\
            //std::string _res_ = client.sendRequest(url);\n\
            <returnStatement>\n\
        }\n\
"

#define TEMPLATE_CLASS "\
<namespaceStart>\
       class <className> : public <interfaceName> {\n\
			public:\n\
				typedef Poco::SharedPtr <<className>> Ptr;\n\
				\n\
				<className>(const TBS::Services::DotNetClientParams & params) : client(params){\n\
				}\n\
				virtual ~<className>() {\n\
				 }\n\n\
				\n\
				\n //methods \n\
				<methods>\n\
				\n\
		private: \n\
				::DotNet::DotNetClient client;\n\
			};\n\
<namespaceEnd>\n\
\n"


#define TEMPLATE_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
#ifndef _<STUBNAME>_dotnetCLIENT_H_\n\
#define _<STUBNAME>_dotnetCLIENT_H_\n\
\n\
#include <Poco/SharedPtr.h>\n\
#include <Poco/BasicEvent.h>\n\
#include <string>\n\
#include <vector>\n\
#include <map>\n\
#include <memory>\n\
#include <sstream>\n\
#include <TBS/Services/DotNet/DotNetServices.h>\n\
#include <DotNet/DotNetClient.h>\n\
#include <jsonrpc/Convertor.h>\n\
#include <Poco/URI.h>\n\
///includes\n\
<includes>\n\
\n\
\n\
<classes>\n\
#endif //_<STUBNAME>_JSONCLIENT_H_\n\
"


#endif
