#ifndef CLIENTTEMPLATE_CLIENT_H_
#define CLIENTTEMPLATE_CLIENT_H_

#define TEMPLATE_CLIENT_METHOD "\
        <returnType> <methodName>(<parameters>){\n\
            ::Json::Value p;\n\
            <parameterAssign>\n\
            <returnStatement>\n\
        }\n\
"

#define TEMPLATE_CLASS "\
<namespaceStart>\
       class <className> : public ::DBus::InterfaceProxy, public <interfaceName> {\n\
			public:\n\
				typedef Poco::SharedPtr <<className>> Ptr;\n\
				\n\
				<className>() : ::DBus::InterfaceProxy(\"<dbusname>\"){\n\
					<connectSignals>\n\
				}\n\
				virtual ~<className>() {\n\
				}\n\n\
				\n\
				static const std::string & dbuspath(){ static std::string val = \"<dbuspath>\"; return val; }\n\
				static const std::string & dbusname(){ static std::string val = \"<dbusname>\"; return val; }\n\
				\n\
				\n //methods \n\
				<methods>\n\
		private: \n\
				<signals>\n\
			};\n\
<namespaceEnd>\n\
\n"


#define TEMPLATE_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
#ifndef _NO_DBUS \n\
#ifndef _<STUBNAME>_DBUSCLIENT_H_\n\
#define _<STUBNAME>_DBUSCLIENT_H_\n\
\n\
#include <Poco/SharedPtr.h>\n\
#include <Poco/BasicEvent.h>\n\
#include <Poco/Exception.h>\n\
#include <string>\n\
#include <string.h>\n\
#include <vector>\n\
#include <map>\n\
#include <memory>\n\
#include <dbus-c++/dbus.h>\n\
#include <dbus/dbus-protocol.h>\n\
///includes\n\
<includes>\n\
\n\
\n\
<classes>\n\
#endif //_<STUBNAME>_DBUSCLIENT_H_\n\
#endif\n\
"


#endif
