/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
 #ifndef _NO_DBUS 
#ifndef _BIORADAR_SERVICE_DBUS_H_
#define _BIORADAR_SERVICE_DBUS_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <TBS/Services/Services.h>
#include <TBS/Services/DBus/DBusServices.h>
///includes
#include "HAL/API/BioRadar.h"

namespace TBS {
	namespace Services {
		class CommunicationChannelHolder;
	}
}

namespace HAL { 
	namespace API { 
		namespace BioRadar { 
			namespace DBus { 
       class Client {
			public:
				typedef Poco::SharedPtr <Client> Ptr;
				
				//with given dbus dispatcher via DBusCommChannelProvider
				Client(TBS::Services::ICommChannelHolder::Ptr ch);
				//with default dbus dispatcher
				Client();
				
				HAL::API::BioRadar::IBase & Base();

				
		private: 
				TBS::Services::ICommChannelHolder::Ptr ch;
				std::auto_ptr<TBS::Services::CommunicationChannelHolder> comChannelHolder;
				HAL::API::BioRadar::IBase::Ptr base_;

			};
			
			
		class Server {
			public:
				typedef Poco::SharedPtr<Server> Ptr;
				//with given dbus dispatcher via DBusCommChannelProvider
				Server(TBS::Services::ICommChannelHolder::Ptr ch);
				//uses default dbus dispatcher
				Server();
				
			public:
				TBS::Services::IServer::Ptr createBase(HAL::API::BioRadar::IBase::Ptr impl);

				
			private:
				TBS::Services::ICommChannelHolder::Ptr ch;
		};
 } 
 } 
 } 
 } 

#endif //_BIORADAR_SERVICE_H_
#endif

