/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _CAMERA_H_
#define _CAMERA_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include "TBS/Services/Types.h"
#include <string>
#include <vector>
#include <map>

namespace TBS{ namespace Services{ namespace Introspection{ class Class; struct Struct; } } } 




namespace HAL { 
	namespace API { 
		namespace Camera { 
	   /** [interface] ICamera:  */
       class GEN_SERVICE_API ICamera {
			public:
				typedef Poco::SharedPtr <ICamera> Ptr;
				
				virtual ~ICamera(){}
				
				static std::string name(){
					static std::string n = "HAL.API.Camera.Camera";
					return n;
				}
				static const ::TBS::Services::Introspection::Class & introspection();
				
 //methods 
				
		/** 
		  * [method] Enable: 
		  */ 
		        virtual void Enable() = 0;

		/** 
		  * [method] Disable: 
		  */ 
		        virtual void Disable() = 0;

		/** 
		  * [method] GoMinEngine: 
		  */ 
		        virtual void GoMinEngine() = 0;

		/** 
		  * [method] GoMaxEngine: 
		  */ 
		        virtual void GoMaxEngine() = 0;

		/** 
		  * [method] GoRelEngine: 
		  * [in] double speed: 
		  */ 
		        virtual void GoRelEngine(const double & speed) = 0;

		/** 
		  * [method] GoMinServo1: 
		  */ 
		        virtual void GoMinServo1() = 0;

		/** 
		  * [method] GoMaxServo1: 
		  */ 
		        virtual void GoMaxServo1() = 0;

		/** 
		  * [method] GoRelServo1: 
		  * [in] double speed: 
		  */ 
		        virtual void GoRelServo1(const double & speed) = 0;

		/** 
		  * [method] GoMinServo2: 
		  */ 
		        virtual void GoMinServo2() = 0;

		/** 
		  * [method] GoMaxServo2: 
		  */ 
		        virtual void GoMaxServo2() = 0;

		/** 
		  * [method] GoRelServo2: 
		  * [in] double speed: 
		  */ 
		        virtual void GoRelServo2(const double & speed) = 0;

		/** 
		  * [method] LightOn: 
		  */ 
		        virtual void LightOn() = 0;

		/** 
		  * [method] LightOff: 
		  */ 
		        virtual void LightOff() = 0;

				
 //signals 
				
				
			};
 } 
 } 
 } 



#endif //_CAMERA_H_

