#ifndef CLIENTTEMPLATE_CLIENT_H_
#define CLIENTTEMPLATE_CLIENT_H_

#define TEMPLATE_CLIENT_METHOD "\
        this.<methodName> = function(<inParams>){\n\
		var jdata;\n\
    	$.jsonrpcTBS({\n\
    		url: settings.url,\n\
    		username: settings.username,\n\
    		password: settings.password,\n\
    		method: \"<methodName>\",\n\
    		params: {<inParamsAssign>},\n\
		onRequest: function (r) {\n\
			//console.log(r);\n\
		},\n\
		onResponse: function (r) {\n\
			//console.log(r);\n\
		},\n\
    		success: function (response) {\n\
    		  jdata = response; //$.parseJSON(response);\n\
		      //return jdata;\n\
    		},\n\
    		fault: function (response, errordata) {\n\
				throw('Failed: ' + response);\n\
    		},\n\
    		error: function (request, status, error) {\n\
    			throw('Failed: ' + error + ')');\n\
    		}\n\
    	});\n\
		\n\
		return jdata; \n\
        }\n\
"

#define TEMPLATE_CLASS "\
function <className>(params){\n\
  var settings = {\n\
      url: params.url + \"<interfaceName>\",\n\
      username: params.username,\n\
      password: params.password,\n\
  };\n\
  \n\
  \n //methods \n\
  <methods>\n\
}\n\
\n"


#define TEMPLATE_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!\n\
 */\n\
\n\
<classes>\n\
"


#endif
