/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _NO_DBUS 
#ifndef _BIORADAR_DBUSCLIENT_H_
#define _BIORADAR_DBUSCLIENT_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <Poco/Exception.h>
#include <string>
#include <string.h>
#include <vector>
#include <map>
#include <memory>
#include <dbus-c++/dbus.h>
#include <dbus/dbus-protocol.h>
///includes
#include "HAL/API/BioRadar.h"


namespace HAL { 
	namespace API { 
		namespace BioRadar { 
			namespace Stub { 
       class BioRadar_DBusClient : public ::DBus::InterfaceProxy, public HAL::API::BioRadar::IBioRadar {
			public:
				typedef Poco::SharedPtr <BioRadar_DBusClient> Ptr;
				
				BioRadar_DBusClient() : ::DBus::InterfaceProxy("com.HAL.API.BioRadar.BioRadar"){
					
				}
				virtual ~BioRadar_DBusClient() {
				}

				
				static const std::string & dbuspath(){ static std::string val = "/com/HAL/API/BioRadar"; return val; }
				static const std::string & dbusname(){ static std::string val = "com.HAL.API.BioRadar.BioRadar"; return val; }
				
				
 //methods 
				virtual void Enable(){		try {
		::DBus::CallMessage call;
		call.member("Enable");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void Disable(){		try {
		::DBus::CallMessage call;
		call.member("Disable");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GoMinBase(){		try {
		::DBus::CallMessage call;
		call.member("GoMinBase");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GoMaxBase(){		try {
		::DBus::CallMessage call;
		call.member("GoMaxBase");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GoRelBase(const double & speed){		try {
		::DBus::CallMessage call;
		::DBus::MessageIter wi = call.writer();

		wi << speed;
		call.member("GoRelBase");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GoMinAntenna(){		try {
		::DBus::CallMessage call;
		call.member("GoMinAntenna");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GoMaxAntenna(){		try {
		::DBus::CallMessage call;
		call.member("GoMaxAntenna");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GoRelAntenna(const double & speed){		try {
		::DBus::CallMessage call;
		::DBus::MessageIter wi = call.writer();

		wi << speed;
		call.member("GoRelAntenna");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual void GetMotorStatus(const bool & isBase, bool & touchMin, bool & touchMax, double & position, bool & positionError){		try {
		::DBus::CallMessage call;
		::DBus::MessageIter wi = call.writer();

		wi << isBase;
		call.member("GetMotorStatus");
		::DBus::Message ret = invoke_method (call);
		::DBus::MessageIter ri = ret.reader();

		ri >> touchMin;
		ri >> touchMax;
		ri >> position;
		ri >> positionError;
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}

virtual std::vector< TBS::Services::Tuple< bool, int32_t > > GetAntenaStatus(){		try {
		::DBus::CallMessage call;
		call.member("GetAntenaStatus");
		::DBus::Message ret = invoke_method (call);
		::DBus::MessageIter ri = ret.reader();

		std::vector< TBS::Services::Tuple< bool, int32_t > > _argout;
		ri >> _argout;
		return _argout;
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}


		private: 
				
			};
 } 
 } 
 } 
 } 



#endif //_BIORADAR_DBUSCLIENT_H_
#endif

