/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _REMOTE_JSONCLIENT_H_
#define _REMOTE_JSONCLIENT_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <jsonrpc/rpc.h>
///includes
#include "HAL/API/Remote.h"


namespace HAL { 
	namespace Remote { 
		namespace Stub { 
       class Movement_JsonClient : public HAL::Remote::IMovement {
			public:
				typedef Poco::SharedPtr <Movement_JsonClient> Ptr;
				
				Movement_JsonClient(jsonrpc::AbstractClientConnector* param){
					this->client = std::auto_ptr<jsonrpc::Client>(new jsonrpc::Client(param));
				}
				Movement_JsonClient(const jsonrpc::HttpClientParams & p){
					this->client = std::auto_ptr<jsonrpc::Client>(new jsonrpc::Client(new jsonrpc::HttpInterfaceClient(HAL::Remote::IMovement::name(), p)));
				}
				virtual ~Movement_JsonClient() {
				 }

				
				
 //methods 
				        void Move(const double & speedLeft, const double & speedRight){
            ::Json::Value pIn;
            pIn["speedLeft"] = jsonrpc::Convertor::cpp2Json< double >(speedLeft); 
pIn["speedRight"] = jsonrpc::Convertor::cpp2Json< double >(speedRight); 

            this->client->CallMethod("Move", pIn);
        }
        void Stop(){
            ::Json::Value pIn;
            pIn = ::Json::nullValue;
            this->client->CallMethod("Stop", pIn);
        }

				
 //signals 
				//TODO
				
		private: 
				std::auto_ptr<jsonrpc::Client> client;
			};
 } 
 } 
 } 



#endif //_REMOTE_JSONCLIENT_H_

